var translations_EN = {
  ABOUT_1: "- where anyone can earn rewards for their content!",
  ABOUT_2: "is powered by Steem platform. App is created by",
  ABOUT_3: "and it is open-source, community driven mobile project. It offers content access for reading, commenting, voting, posting, transfer earnings, etc. features offered by Steem blockchain and Steemit.",
  ABOUT_4: "1. App never access or hold onto user funds",
  ABOUT_5: "2. App offer a client-side security model, with private keys hosted locally and never sent to any servers.",
  ABOUT_6: "3. App offers simple, attractive user interfaces and experiences",
  ABOUT_7: "4. App never require users to input any personal information",
  ABOUT_8: "Vote good-karma as witness",

  exchange_1: "Price",
  exchange_2: "Amount",
  exchange_3: "Total",
  exchange_4: "No open orders for",
  exchange_5: "Date",
  exchange_6: "Buy",
  exchange_7: "Sell",
  exchange_8: "Open",
  exchange_9: "History",

  follow_1: "Follow back",
  follow_2: "Followed",
  follow_3: "Unfollow",
  follow_4: "Following",

  menu_1: "Profile",
  menu_2: "Follow",
  menu_3: "Logout",
  menu_4: "Login",
  menu_5: "Home",
  menu_6: "Bookmarks",
  menu_7: "Transfer",
  menu_8: "Market",
  menu_9: "Settings",
  menu_10: "About",

  post_1: "Menu",
  post_2: "Bookmark",
  post_3: "Reblog",
  post_4: "Downvote",
  post_5: "Unvote Downvoted",
  post_6: "Upvote",
  post_7: "Unvote Upvoted",
  post_8: "Reply",
  post_9: "Edit",

  posts_1: "Trending",
  posts_2: "Hot",
  posts_3: "New",
  posts_4: "Active",
  posts_5: "Promoted",
  posts_6: "Trending 30",
  posts_7: "Votes",
  posts_8: "Comments",
  posts_9: "Payout",
  Resteemed by
  Upvote
  Load More
  Feed

  post_10: "",
  post_11: "",
  follow_1: "",
  follow_1: "",
  follow_1: "",
  follow_1: "",
  follow_1: "",
  follow_1: "",
  follow_1: "",                         {{ 'posts_' | translate }}
  follow_1: "",
  follow_1: "",
  follow_1: "",
  follow_1: "",
  follow_1: "",
  follow_1: "",
  follow_1: "",
  follow_1: "",
  follow_1: "",
}
  {{ 'post_1' | translate }}
